project_owner           = "nhs-uec"
vpc_name                = "sm-vpc"
vpn_security_group_name = "vpn-sg"
tag_version             = "1"
service                 = "dos"
cost_centre             = "primary-care-network"
data_classification     = "5"
data_type               = "pii"
