environment           = "dev"
vpc_cidr_block_marker = "150"
data_classification   = "1"
data_type             = "PII"
project_type          = "dev"
public_facing         = "n"
service_category      = "Bronze"
on_off_pattern        = "MF86"
