environment           = "test"
vpc_cidr_block_marker = "151"
data_classification   = "3"
data_type             = "PII"
project_type          = "alpha"
public_facing         = "n"
service_category      = "gold"
on_off_pattern        = "alwaysOn"
