name: Pipeline Deployment Application Development Environment

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  metadata:
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.13
  quality_check:
    name: "Quality Check"
    uses: NHSDigital/uec-dos-management/.github/workflows/quality_checks.yaml@v0.13
    needs:
      [
        metadata,
      ]
    with:
      environment: dev
      workspace: ${{ needs.metadata.outputs.workspace }}
      stacks: '["github-runner", "terraform_management", "application", "support_tools"]'
    secrets: inherit
  unit-tests:
    name: Unit Test
    needs:
      [
        metadata,
        quality_check,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/unit_test.yaml@v0.13
    with:
      env: dev
    secrets: inherit
  deploy-application-infrastructure:
      needs:
        [
          quality_check,
          metadata,
        ]
      uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.13
      with:
        environment: dev
        domain: "uec-dos-service-management"
        workspace: ${{ needs.metadata.outputs.workspace }}
        stacks: '["application", "support_tools"]'
        action: apply
      secrets: inherit
  build-and-deploy-application-code:
    name: Build and deploy application
    needs:
      [
        metadata,
        deploy-application-infrastructure
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-and-deploy-application.yaml@v0.13
    with:
      environment: dev
      workspace: ${{ needs.metadata.outputs.workspace }}
      services:
        "[
          'healthcare-services-data-manager',
          'locations-data-manager',
          'organisation-affiliations-data-manager',
          'organisations-data-manager',
          'questionnaire-responses-data-manager',
          'questionnaires-data-manager',
          'org_data_load',
          'locations_data_load',
          'organisation_affiliations_data_load',
          'service_data_load'
        ]"
    secrets: inherit
  slack-notifications:
    name: Send notification to slack
    needs: [
      metadata,
      quality_check,
      unit-tests,
      deploy-application-infrastructure,
      build-and-deploy-application-code,
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.13
    with:
      env: dev
    secrets: inherit
