name: Pipeline Cleardown Application Development Environment

on:
  delete:
    branches:
      - 'task/*'
jobs:
  destroy:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    uses: ./.github/workflows/action-infrastructure-cleardown.yaml
    with:
      github_environment: dev
      branch_name: ${{ github.event.ref }}
    secrets: inherit
  summarise:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "Ref for a branch deletion: ${{ github.event.ref }}"
          echo "Ref type for a branch deletion: ${{ github.event.ref_type }}"
  slack-notifications:
    needs: [
      destroy
    ]
    uses: ./.github/workflows/slack-notifications.yaml
    with:
      env: dev
    secrets: inherit # pass slack webhookurl


