name: Pipeline Deploy Account Level Infrastructure

on:
  push:
    branches:
      - 'main'

jobs:
    metadata:
      name: "Get Metadata"
      uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.42
    deploy-account-infrastructure-apply-dev:
      name: "Deploy Account Level Infrastructure to dev account"
      needs:
        [
          metadata,
        ]
      uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.42
      with:
        environment: dev
        domain: "uec-dos-service-management"
        workspace: ${{ needs.metadata.outputs.workspace }}
        stacks: '["network", "aurora", "terraform_management", "github-runner"]'
        action: apply
      secrets: inherit
    deploy-account-infrastructure-apply-int:
        name: "Deploy Account Level Infrastructure to int account"
        needs:
          [
            metadata,
          ]
        uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.42
        with:
          environment: int
          domain: "uec-dos-service-management"
          workspace: ${{ needs.metadata.outputs.workspace }}
          stacks: '["network", "terraform_management", "github-runner"]'
          action: apply
        secrets: inherit
    deploy-account-infrastructure-apply-test:
      name: "Deploy Account Level Infrastructure to test account"
      needs:
        [
          metadata,
        ]

      uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.42
      with:
        environment: test
        domain: "uec-dos-service-management"
        workspace: ${{ needs.metadata.outputs.workspace }}
        stacks: '["network", "terraform_management", "github-runner"]'
        action: apply
      secrets: inherit
    deploy-account-infrastructure-apply-preprod:
        name: "Deploy Account Level Infrastructure to preprod account"
        needs:
          [
            metadata,
          ]
        uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.42
        with:
          environment: preprod
          domain: "uec-dos-service-management"
          workspace: ${{ needs.metadata.outputs.workspace }}
          stacks: '["network", "terraform_management", "github-runner"]'
          action: apply
        secrets: inherit
    slack-notifications:
      name: Send notification to slack
      needs: [
        metadata,
        deploy-account-infrastructure-apply-dev,
        deploy-account-infrastructure-apply-test,
        deploy-account-infrastructure-apply-int,
        deploy-account-infrastructure-apply-preprod
      ]
      if: always()
      uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.42
      with:
        env: dev
      secrets: inherit


