name: Pipeline Deployment Application Test Environment

on:
  workflow_call:
    inputs:
      workspace:
        description: "The workspace to deploy the service into"
        required: true
        type: string
      tag:
        description: "Defines the tag to be used for deployment"
        required: true
        type: string
jobs:
  deploy-application-infrastructure:
    name: Deploy application infrastructure
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.7
    with:
      environment: test
      workspace: ${{ inputs.workspace }}
      domain: "uec-dos-service-management"
      stacks: "['application']"
      tag: ${{ inputs.tag }}
      action: apply
    secrets: inherit
  build-and-deploy-application:
    name: Build and deploy application
    needs:
      [
        deploy-application-infrastructure,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-and-deploy-application.yaml@v0.7
    with:
      environment: test
      workspace: ${{ inputs.workspace }}
      services: "[
          'healthcare-services-data-manager',
          'locations-data-manager',
          'organisation-affiliations-data-manager',
          'organisations-data-manager',
          'questionnaire-responses-data-manager',
          'questionnaires-data-manager',
        ]"
      tag: ${{ inputs.tag }}
    secrets: inherit
  integration-test:
      needs:
        [
          deploy-application-infrastructure,
          build-and-deploy-application,
        ]
      name: Run integration tests
      uses: ./.github/workflows/integration-test.yaml
      with:
        github_environment: test
        DEPLOYMENT_WORKSPACE: ${{ inputs.workspace }}
      secrets: inherit
