name: Pipeline Cleardown Application Development Environment

on:
    delete
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "I am the ref for a branch deletion: ${{ github.event.ref }}"
          echo "I am the ref_type for a branch deletion: ${{ github.event.ref_type }}"
 