name: Pipeline Cleardown Application Test Environment

on:
  pull_request:
    types:
      - closed
jobs:
  temp:
    name: temp
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "triggering action: ${{ github.event_name }}"
          echo "ref type: ${{ github.ref_type }}"
          echo "triggering reference: ${{ github.ref_name }}"
          echo "github.event.ref : ${{ github.event.ref }}"
          echo "github.event.ref.type : ${{ github.event.ref_type }}"
          echo "github.head_ref" ${{github.head_ref }}
          echo "username of user triggering the workflow: ${{ github.actor }}"
  metadata:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.11
  destroy:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    uses: NHSDigital/uec-dos-management/.github/workflows/infrastructure-cleardown.yaml@v0.11
    needs:
      [
        metadata,
      ]
    with:
      environment: test
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-service-management"
      stacks: '["application", "support_tools"]'
    secrets: inherit

  summarise:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "${{ github.actor }} deleted a task branch..."
          echo "triggering cleardown of infra in test account relating to ${{ github.ref_type }}: ${{ github.event_ref }}"

  slack-notifications:
    name: Send notification to slack
    needs: [
      destroy,
      summarise,
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.11
    with:
      env: test
    secrets: inherit
