name: Pipeline Deployment Application Test Environment

on:
  workflow_call:
    inputs:
      git_tag:
        description: "Defines git commit tag to be used for deployment"
        required: true
        type: string

jobs:
  metadata:
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.5
  deploy-application-infrastructure:
    needs:
      [
        metadata,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.5
    with:
      environment: test
      domain: "uec-dos-service-management"
      workspace: ${{ needs.metadata.outputs.workspace }}
      stacks: "['application']"
      action: apply
    secrets: inherit
  deploy-support-tools-infrastructure:
    uses: ./.github/workflows/action-infrastructure-stack.yaml
    with:
      github_environment: test
      stack: support_tools
      action: plan
      deployment_workspace: default
    secrets: inherit
  build-and-deploy-application-code:
    name: Build and deploy application
    needs:
      [
        metadata,
        deploy-application-infrastructure
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-and-deploy-application.yaml@v0.5
    with:
      environment: dev
      workspace: ${{ needs.metadata.outputs.workspace }}
      services:
        "[
          'healthcare-services-data-manager',
          'locations-data-manager',
          'organisation-affiliations-data-manager',
          'organisations-data-manager',
          'questionnaire-responses-data-manager',
          'questionnaires-data-manager',
          'org_data_load',
          'locations_data_load',
          'organisation_affiliations_data_load',
          'service_data_load'
        ]"
    secrets: inherit
  integration-test:
      needs:
        [
          deploy-application-infrastructure,
          build-and-deploy-application-code,
          derive-deployment-workspace,
        ]
      name: Run integration tests
      uses: ./.github/workflows/integration-test.yaml
      with:
        github_environment: test
        DEPLOYMENT_WORKSPACE: ${{ needs.derive-deployment-workspace.outputs.deployment_workspace }}
      secrets: inherit




