name: Push to branch workflow

on:
  push:
    branches:
      # - main
      # - 'task/*'
      - 'task/DR-1122_Refactor_work_flows'

jobs:

  run-pipeline:
    name: "Run pipeline for push to branch"
    uses: ./.github/workflows/pipeline-deploy.yaml
    with:
      environment: dev
    secrets: inherit

  slack-notifications:
    name: Send notification to slack
    needs: [
      run-pipeline,
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@latest
    with:
      env: dev
    secrets: inherit
