name: Scan Dependencies

on:
  workflow_call:

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./scripts/sbom-generator.sh
      - uses: actions/upload-artifact@v3
        with:
          name: sbom-spdx.json
          path: ./sbom-spdx.json
      - run: |
          ./scripts/cve-scanner.sh
      - uses: actions/upload-artifact@v3
        with:
          name: cve-scan.json
          path: ./cve-scan.json

